### ISSUE TITLE
Better naming of subscribers and publisher

### ISSUE THREAD

**Issue by mstoelzle** [tud-cor-sr/ros2-elastica#18]
Please use a more intuitive name for the publisher and subscriber class attributes:
https://github.com/tud-cor-sr/ros2-elastica/blob/main/elastica_sim_control/elastica_sim_control/elastica_publisher_subscriber.py#L41

**Comment by RUFFY-369** [comment]
Yeah sure, those were needed to be changed from just numbers.
Also, are the ros topic names fine?

**Comment by mstoelzle** [comment]
The topic names should also be ROS parameters specified in the config. The default value should be in the elastica namespace `/elastica/physical_params`, `/elastica/rod_state`, `/elastica/muscle_torque_control_points` and `/elastica/uniform_torques`

**Comment by RUFFY-369** [comment]
Okay that will be a more standard way for naming the ros topics. Separate params for each package naming their respective ros topics

**Comment by RUFFY-369** [comment]
Hi @mstoelzle , Solved in recent commits

**Comment by mstoelzle** [comment]
I think what is still missing is to specify the publication and subscription topic names through ROS parameters. And the default topic name (e.g. if not specified otherwise in the ROS parameters) should be in the `elastica` name space. This means that you need to remove the `/` at the beginning of the default topic name:

https://github.com/tud-cor-sr/ros2-elastica/blob/main/elastica_sim/elastica_sim/elastica_publisher_subscriber.py#L37

**Comment by RUFFY-369** [comment]
Oh! My bad, i missed changing the namespace for the ros topics. I will make the necessary changes.

**Comment by RUFFY-369** [comment]
Hi @mstoelzle , I pushed the new topic names in config in the recent commits. Please review them
